[general]
separator = "|"

[cpu]
time = 1000
name = "CPU"
icon = " "

[memory]
time = 1000
name = "RAM"
icon = " "

[temperature]
time = 1000
name = "TEMP"
icon = "󰏈 " 

[disk]
time = 2000
name = "DISK"
icon = "󰋊 "
unit = "/"

[volume]
time = 100
name = "VOL"
icon_active = " " 
icon_muted = "󰖁 " 

[network]
time = 5000
name = "NET"
icon_up = "󰀂 " 
icon_down = "󰯡 " 

# [battery]
# time = 5000
# name = "BAT"
# icon_full = "󰁹" 
# icon_medium = "󰁿" 
# icon_low = "󰁺" 
# path = "/sys/class/power_supply/BAT0/capacity"

[date]
time = 1000
format = "%A %d/%m/%Y %H:%M"
icon = " "
